"""End-to-end tests for ``scripts/export_api.py --check``.

These tests run the script as a subprocess so they exercise the
same entry point CI uses. They never touch the real
``docs/data/api.json`` — each test points ``--out`` at a temp file
and seeds it with a known payload, then verifies the script's
exit code + stderr.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def _run(out_path: Path) -> subprocess.CompletedProcess:
    """Invoke ``python scripts/export_api.py --check --out <out_path>``."""
    return subprocess.run(
        [
            sys.executable,
            "scripts/export_api.py",
            "--check",
            "--out",
            str(out_path),
        ],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _live_payload() -> dict:
    """Generate the live payload via the script itself in default mode.

    We do not want to mock the registry — the point of these tests
    is to detect mismatches between what the script would write
    and what is on disk.
    """
    out = REPO_ROOT / "docs" / "data" / "api.json"
    # If api.json was deleted between runs, recreate it.
    if not out.is_file():
        subprocess.run(
            [sys.executable, "scripts/export_api.py", "--out", str(out)],
            cwd=str(REPO_ROOT),
            check=True,
        )
    return json.loads(out.read_text(encoding="utf-8"))


def test_check_passes_when_file_matches_live(tmp_path: Path) -> None:
    """A file regenerated by the script itself passes ``--check``."""
    out = tmp_path / "api.json"
    # Write the live payload verbatim.
    _write_json(out, _live_payload())
    proc = _run(out)
    assert proc.returncode == 0, (
        f"--check unexpectedly failed:\nstdout: {proc.stdout}\nstderr: {proc.stderr}"
    )
    assert "is up to date" in proc.stdout


def test_check_fails_on_stale_function_count(tmp_path: Path) -> None:
    """A file with the wrong ``function_count`` must trip ``--check``."""
    out = tmp_path / "api.json"
    payload = _live_payload()
    payload["function_count"] = payload["function_count"] - 1
    _write_json(out, payload)
    proc = _run(out)
    assert proc.returncode != 0
    assert "function_count" in proc.stderr or "stale" in proc.stderr


def test_check_fails_on_wrong_version(tmp_path: Path) -> None:
    """A file with the wrong ``pyspt_version`` must trip ``--check``."""
    out = tmp_path / "api.json"
    payload = _live_payload()
    payload["pyspt_version"] = "999.999.999"
    _write_json(out, payload)
    proc = _run(out)
    assert proc.returncode != 0
    assert "pyspt_version" in proc.stderr


def test_check_fails_on_added_function(tmp_path: Path) -> None:
    """A file missing a function must trip ``--check``."""
    out = tmp_path / "api.json"
    payload = _live_payload()
    # Drop one function from the on-disk copy; live will have it.
    funcs = payload["functions"]
    first_key = next(iter(funcs))
    del payload["functions"][first_key]
    payload["function_count"] = len(payload["functions"])
    _write_json(out, payload)
    proc = _run(out)
    assert proc.returncode != 0
    assert "stale" in proc.stderr or "function-level payload" in proc.stderr


def test_check_fails_when_file_missing(tmp_path: Path) -> None:
    """A missing file must trip ``--check`` with a clear message."""
    out = tmp_path / "nope.json"
    proc = _run(out)
    assert proc.returncode != 0
    assert "not found" in proc.stderr


def test_check_fails_on_invalid_json(tmp_path: Path) -> None:
    """A file that isn't valid JSON must trip ``--check`` loudly."""
    out = tmp_path / "bad.json"
    out.write_text("this is not json {", encoding="utf-8")
    proc = _run(out)
    assert proc.returncode != 0
    assert "not valid JSON" in proc.stderr


def test_check_never_writes_files(tmp_path: Path) -> None:
    """``--check`` must not modify ``--out`` (or anything else)."""
    out = tmp_path / "api.json"
    payload = _live_payload()
    _write_json(out, payload)
    before = out.read_text(encoding="utf-8")
    proc = _run(out)
    assert proc.returncode == 0
    after = out.read_text(encoding="utf-8")
    # Timestamps differ by seconds at most; the normalised content
    # (everything except generated_at) must be identical.
    before_payload = json.loads(before)
    after_payload = json.loads(after)
    assert before_payload["pyspt_version"] == after_payload["pyspt_version"]
    assert before_payload["function_count"] == after_payload["function_count"]
    assert before_payload["functions"] == after_payload["functions"]


@pytest.fixture(scope="module", autouse=True)
def _ensure_real_api_json_exists() -> None:
    """Make sure the real ``docs/data/api.json`` exists for other tests.

    Some tests above call ``_live_payload()`` which depends on the
    file having been generated by an earlier run. If a previous test
    or developer wiped it, regenerate it once per module.
    """
    out = REPO_ROOT / "docs" / "data" / "api.json"
    if not out.is_file():
        subprocess.run(
            [sys.executable, "scripts/export_api.py", "--out", str(out)],
            cwd=str(REPO_ROOT),
            check=True,
        )
