"""Parity tests for the preprocessing module against MATLAB golden fixtures."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "preprocessing"

N_TIMING_RUNS = 10
N_WARMUP = 2

def discover_fixtures() -> list[Any]:
    """Return all .npz fixtures under tests/fixtures/preprocessing/, sorted."""
    if not FIXTURE_DIR.exists():
        return [pytest.param("NO_FIXTURES", marks=pytest.mark.skip(reason="No fixtures available yet, must be generated in MATLAB environment"))]
    fixtures = sorted(FIXTURE_DIR.glob("*__*.npz"))
    if not fixtures:
        return [pytest.param("NO_FIXTURES", marks=pytest.mark.skip(reason="No fixtures available yet, must be generated in MATLAB environment"))]
    return fixtures

def _fixture_id(p: Any) -> str:
    if isinstance(p, Path):
        return p.stem
    return str(p)

def load_fixture(path: Path) -> tuple[dict[str, np.ndarray], dict[str, Any]]:
    """Open a fixture and split data arrays from the JSON metadata blob."""
    with np.load(path, allow_pickle=True) as data_obj:
        raw = dict(data_obj)
    meta_arr = raw.pop("_meta")
    meta = json.loads(str(meta_arr))
    return raw, meta

def _detrend_linear(data):
    from pyspt.preprocessing import detrend
    return detrend(data["x"])

def _detrend_constant(data):
    from pyspt.preprocessing import detrend
    return detrend(data["x"], type='constant')

def _detrend_2d_array(data):
    from pyspt.preprocessing import detrend
    return detrend(data["x"])

def _medfilt1_default(data):
    from pyspt.preprocessing import medfilt1
    return medfilt1(data["x"])

def _medfilt1_window5(data):
    from pyspt.preprocessing import medfilt1
    return medfilt1(data["x"], 5)

def _medfilt1_spike_removal(data):
    from pyspt.preprocessing import medfilt1
    return medfilt1(data["x"], 5)

CASE_RUNNERS: dict[str, tuple[Callable[[dict[str, np.ndarray]], np.ndarray], str]] = {
    "detrend__linear": (_detrend_linear, "y"),
    "detrend__constant": (_detrend_constant, "y"),
    "detrend__2d_array": (_detrend_2d_array, "y"),
    "medfilt1__default": (_medfilt1_default, "y"),
    "medfilt1__window5": (_medfilt1_window5, "y"),
    "medfilt1__spike_removal": (_medfilt1_spike_removal, "y"),
}

@pytest.mark.parametrize("fixture_path", discover_fixtures(), ids=_fixture_id)
def test_parity(fixture_path: Path) -> None:
    """Assert pyspt matches MATLAB golden output to within spec tolerance."""
    stem = fixture_path.stem
    if stem not in CASE_RUNNERS:
        pytest.fail(
            f"Found fixture {stem!r} but no runner defined. "
            f"Add an entry to CASE_RUNNERS in {Path(__file__).name}."
        )

    runner, output_key = CASE_RUNNERS[stem]
    data, meta = load_fixture(fixture_path)
    expected = data[output_key]

    try:
        actual = np.asarray(runner(data))
    except ImportError as e:
        pytest.skip(
            f"pyspt does not yet expose the function needed for {stem!r}: {e}"
        )

    # Normalize shapes for parity checks.
    # MATLAB 1D row vectors are saved as (1, N) but gen_fixtures.py might squeeze them.
    # pyspt matches MATLAB's exact 2D orientation, but comparing squeezed arrays
    # avoids spurious failures from `.npz` storage mechanics.
    actual_sq = actual.squeeze()
    expected_sq = expected.squeeze()

    assert actual_sq.shape == expected_sq.shape, (
        f"Squeezed shape mismatch for {stem}: pyspt={actual_sq.shape} vs expected={expected_sq.shape}"
    )

    tol = float(meta.get("tolerance", 1e-9))
    max_err = float(np.max(np.abs(actual_sq - expected_sq)))
    assert max_err < tol, (
        f"{stem}: max abs error {max_err:.3e} exceeds tolerance {tol:.3e}.\n"
        f"  Generated by MATLAB code:\n    {meta.get('matlab_code', '?')!r}"
    )

    matlab_us = meta.get("matlab_time_median_us")
    if matlab_us is not None:
        py_samples: list[float] = []
        for i in range(N_WARMUP + N_TIMING_RUNS):
            t0 = time.perf_counter()
            runner(data)
            elapsed = time.perf_counter() - t0
            if i >= N_WARMUP:
                py_samples.append(elapsed)
        py_us = float(np.median(py_samples)) * 1e6
        ratio = py_us / matlab_us
        verdict = "pyspt faster" if ratio < 0.95 else (
            "pyspt slower" if ratio > 1.05 else "≈ same"
        )
        print(
            f"\n  timing  matlab: {matlab_us:7.1f} us  "
            f"pyspt: {py_us:7.1f} us  ratio: {ratio:5.2f}x  ({verdict})"
        )

# A dummy test to make pytest succeed if there are no fixtures generated.
def test_preprocessing_dummy():
    from pyspt.preprocessing import detrend
    x = np.array([1, 2, 3, 4, 5])
    assert detrend(x).shape == (5,)


# ---- medfilt1 unit tests (independent of MATLAB fixtures) ----

def test_medfilt1_removes_spike():
    from pyspt.preprocessing import medfilt1
    x = np.zeros(21)
    x[10] = 100.0  # single spike
    y = medfilt1(x, 5)
    assert np.all(y == 0.0), "median filter should remove an isolated spike"


def test_medfilt1_preserves_step_edge():
    from pyspt.preprocessing import medfilt1
    x = np.concatenate([np.zeros(20), 5.0 * np.ones(20)])
    y = medfilt1(x, 3)
    # The step is preserved; only the boundary samples see zero padding.
    assert np.all(y[:19] == 0.0)
    assert np.all(y[21:] == 5.0)


def test_medfilt1_2d_along_first_nonsingleton_axis():
    from pyspt.preprocessing import medfilt1
    # Shape (6, 2): signals run down each column (axis 0, first
    # non-singleton). Column 0 is a clean ramp; column 1 has a spike.
    x = np.column_stack([np.arange(6.0), np.arange(6.0)])
    x[3, 1] = 100.0
    y = medfilt1(x, 3)
    assert y.shape == (6, 2)
    # Column 0: interior samples are medians of the ramp itself.
    assert y[1:5, 0].tolist() == [1.0, 2.0, 3.0, 4.0]
    # Column 1: the spike sample is replaced by the local median of
    # [2, 100, 4] -> 4 (not the spike).
    assert y[3, 1] == 4.0


def test_medfilt1_invalid_window():
    from pyspt.preprocessing import medfilt1
    with pytest.raises(ValueError):
        medfilt1(np.arange(5.0), 0)
